PHARMACY-26: Рисуем лендинг на тематику ВКР
SleptsovBoris/pharmacy pull request #2
Opened 2023-01-08 16:44 UTC by SleptsovBoris

Отрисовали лендинг на тематику ВКР

2023-01-12 17:24 UTC, karauul commented on .prettierrc.json
> +  "autocrlf": false,
endOfLine: lf

2023-01-12 17:29 UTC, karauul commented on src/App.tsx
> +  'Добро пожаловать в аптеку Бориса. Здесь вы можете найти необходимые вам лекарства по самой высокой цене. Мы на рынке уже 1 год. Приобретаете лекарства и будьте здоровы! Наш адрес улица Маяковская.
проверь текст

2023-01-14 20:43 UTC, VladislavAripov commented on src/App.tsx
> +  'Добро пожаловать в аптеку Бориса. Здесь вы можете найти необходимые вам лекарства по самой высокой цене. Мы на рынке уже 1 год. Приобретаете лекарства и будьте здоровы! Наш адрес улица Маяковская.
Переименуй переменную в aboutText и поправь содержание

2023-01-14 20:53 UTC, VladislavAripov requested changes

2023-01-14 20:53 UTC, VladislavAripov commented on .vscode/settings.json
> +}
Добавь .vscode в .gitignore

2023-01-14 20:53 UTC, VladislavAripov commented on src/App.tsx
> +          © Все права защищены. ООО &quot; Аптека Бориса &quot;
Лишние пробелы перед и после "Аптека Бориса. &quot; должен стоять впритык

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Cart/components/CartItemsTab/CartItemsTab.tsx
> +export default CartItemsTab;
Добавь отступ между компонентом и экспортом

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Cart/components/OrdersTab/OrdersTab.tsx
> +export default OrdersTab;
Отступ

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Products/Products.tsx
> +    },
Заполни описание товаров

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Products/Products.tsx
> +export default Products;
Отступ

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Products/components/Product/Product.tsx
> +            </div> */}
Лишний код

2023-01-14 20:53 UTC, VladislavAripov commented on src/components/Products/components/Product/Product.tsx
> +export default Product;
Отступ

2023-01-14 20:53 UTC, VladislavAripov commented on src/constants/cookiesNames.ts
> +export default cookiesNames;
Отступ

2023-01-14 20:53 UTC, VladislavAripov commented on tsconfig.json
>  }
Съехали отступы, отформатируй файл через ctrtl + s

2023-02-05 11:32 UTC, VladislavAripov approved these changes

2023-02-05 11:32 UTC, merged